### ISSUE TITLE
Tested in OSX ElCapitan fails

### ISSUE THREAD

**Issue by fbaquero** [kontrol0/K0SASP#1]
Installer closes unexpected when finishing and searchsploit.app does'n work.

**Comment by kontrol0** [comment]
http://www.kontrol0.com/2015/11/como-instalar-k0sasp-en-osx-1011-el.html

2015-11-09 20:43 GMT+01:00 FBaquero notifications@github.com:

**Comment by fbaquero** [comment]
Thanks!

> http://www.kontrol0.com/2015/11/como-instalar-k0sasp-en-osx-1011-el.html

**Comment by robin-williams** [comment]
I am having a similar issue after setting things up as noted in the url for the fix...it still just fails on El Captain period. It will not even install.
